### PR TITLE
persist: Fix txn-wal filter pushdown looking up wrong column name

### PR DESCRIPTION
**Pull request by def-**
`TxnsCodecRow::should_fetch_part` looked up column "key" instead of "ok", silently disabling per-shard filter pushdown since SourceData has no such field. Introduced in #29151.

### CODE REVIEW

**Review by DAlperin — APPROVED** [review]
We should probably make this a const
