### ISSUE TITLE
regression: "environmentd: unknown cluster replica size" on startup

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16747]
### What version of Materialize are you using?

9d2acaaf4462f1fb2597ea5c926b1d835e56cc66

### How did you install Materialize?

Docker image

### What is the issue?

The launchdarkly test has started failing in Nightly. Bisection reveals that it started failing after this commit:

```
commit 9d2acaaf4462f1fb2597ea5c926b1d835e56cc66
Author: umanwizard <brennan@materialize.com>
Date:   Mon Dec 19 16:40:58 2022 -0500

    Allow custom compaction windows on builtin tables (#16658)
    
    Allow custom compaction windows on builtin tables,
    and use that feature to force at least 30 days of history for the tables that
    are necessary for querying `mz_cluster_replica_utilization`,
    i.e. `mz_cluster_replica_sizes`, `mz_cluster_replica_metrics`, and
    `mz_cluster_replicas`.
```

What happens is that after the Mz is restarted by the test for the N-th time, it fails to start as follows:

```
environmentd: 2022-12-20T08:52:06.818493Z  INFO mz_adapter::coord: coordinator init: beginning
environmentd: 2022-12-20T08:52:06.818615Z  INFO mz_adapter::coord: coordinator init: opening catalog
environmentd: unknown cluster replica size 4-4
```

My guess is that `mz_cluster_replica_sizes` gets compacted away? 

I do not know why only this test is failing and none of our other restart-heavy tests. The test does not mess with the `mz_cluster_replica_sizes` in any way.

@umanwizard 

### Relevant log output

```source
environmentd: unknown cluster replica size 4-4
```

**Comment by philip-stoev** [comment]
There is also merge skew:

```


error[E0063]: missing field `is_retained_metrics_relation` in initializer of `BuiltinTable`
--
  | --> src/adapter/src/catalog/builtin.rs:1673:76
  | \|
  | 1673 \| pub static MZ_CLUSTER_REPLICA_FRONTIERS: Lazy<BuiltinTable> = Lazy::new(\|\| BuiltinTable {
  | \|                                                                            ^^^^^^^^^^^^ missing `is_retained_metrics_relation`
  |  
  | For more information about this error, try `rustc --explain E0063`.
  | error: could not compile `mz-adapter` due to previous error

```

**Comment by lluki** [comment]
Some initial investigation:
 * When environmentd starts in the test, environmentd thinks that the allowed cluster sizes are `["2xsmall", "xsmall", "small", "medium", "large", "xlarge"]` so environmentd thinks we are running in a kubernetes controlled production environment (in development the valid size options are of the form '1', '4-4' etc)
 * Environmentd loads a catalog that has a replica size '4-4', which will then crash it on startup.
 * I have no idea (yet) why we store in the catalog a replica of size '4-4', our default replicas have size '1' and the test is not perfoming any cluster operations. But presumably it would also fail with size '1' as it is not in the allowed list of sizes.

**Comment by philip-stoev** [comment]
@aalexandrov is on it, he has a candidate fix PR

**Comment by philip-stoev** [comment]
I am removing the release blocker tag -- after discussion with @aalexandrov this, while not being 100% a test/CI issue alone, does not require blocking the release as the impact on the cloud would be much more limited.

Separately from any code changes that may come out of his investigation, he had made adjustments in the launcharkly UI that made Nightly to become green again on main.
