### PR TITLE
Quick fix for merge skew with UuidGenerateV5

### PR DESCRIPTION
**Pull request by def-**
```
error[E0004]: non-exhaustive patterns: `&BinaryFunc::UuidGenerateV5` not covered
    --> src/expr/src/scalar/func.rs:2515:15
     |
2515 |         match self {
     |               ^^^^ pattern `&BinaryFunc::UuidGenerateV5` not covered
```

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

### CODE REVIEW

**Comment by def-** [comment]
@dseisun-materialize From what I can tell uuid_generate_v5 only returns NULL when one of its parameters is NULL, is that correct?

**Comment by mgree** [comment]
That looks right to me. Since nulls are only returned by propagating null inputs, I would change [Binary_func::output_type](https://github.com/def-/materialize/blob/270bec9156c20eacef48f1c1ae5f392f11099af8/src/expr/src/scalar/func.rs#L2472) to say:

```Rust
            UuidGenerateV5 => ScalarType::Uuid.nullable(in_nullable),
```

That is, if given a non-nullable input type, the result of UUID generation can be guaranteed to not be null.

**Review by jkosh44 — APPROVED** [review]

**Review by antiguru — APPROVED** [review]
